### ISSUE TITLE
Логика была другая, бонус считается от суммы выше 10000

### ISSUE THREAD

**Issue by coursar** [EgorovAA/Bonus#3]
https://github.com/EgorovAA/Bonus/blob/cde04779a050c1ab48f6b4084ab030f53fcaa303/src/lib.js#L5-L7

**Comment by EgorovAA** [comment]
Я не включил 10000 , только знак > стоит

**Comment by coursar** [comment]
Я не о том, я о том, что если продажник продал на 12000, то бонус считается с 2000, а не 12000
